# .upptimerc.yml
# This file is used to configure the Upptime status page.
# See https://upptime.js.org/docs/configuration for more information.
owner: lezwatch
repo: upptime

assignees:
  - ipstenu

sites:
  - name: LezWatch.TV
    url: https://lezwatchtv.com
  - name: Documentation
    url: https://docs.lezwatchtv.com

status-website:
  cname: status.lezwatchtv.com
  logoUrl: https://status.lezwatchtv.com/logo.svg
  name: LezWatch.TV Status
  favicon: https://status.lezwatchtv.com/favicon.ico
  faviconSvg: https://status.lezwatchtv.com/favicon.svg
  introTitle: "Status of **LezWatch.TV** - The Greatest Database of Queer Female, Non-Binary, and Transgender TV"
  introMessage: "Keep up to date with our site status here and don't forget to check out the [**main site**](https://lezwatchtv.com) for more information on Queer TV."
  navbar:
    - title: LWTV
      href: https://lezwatchtv.com
    - title: Docs.
      href: https://docs.lezwatchtv.com
  themeUrl: https://status.lezwatchtv.com/style.css?version=1.0.0
  customHeadHtml: "<script async defer src='https://uptime.ipstenu.com/tracker.js' data-website-id='cmhzhkoua00st10i1ieifjfq0'></script>"
