# .upptimerc.yml
# This file is used to configure the Upptime status page.
# See https://upptime.js.org/docs/configuration for more information.
owner: lezwatch
repo: upptime

sites:
  - name: LezWatch.TV
    url: https://www.lezwatchtv.com
  - name: Documentation
    url: https://docs.lezwatchtv.com

status-website:
  # Use cname for custom domain, or comment the `cname` line if you don't have a domain
  cname: status.lezwatchtv.com
  # Use baseUrl for the GitHub Pages URL (i.e. use <repo> from https://<owner>.github.io/<repo>/), or comment the `baseUrl` line if you use a custom domain
  # baseUrl: /upptime
  logoUrl: https://status.lezwatchtv.com/logo.svg
  name: LezWatch.TV Status
  favicon: https://status.lezwatchtv.com/favicon.ico
  faviconSvg: https://status.lezwatchtv.com/favicon.svg
  introTitle: "Status of **LezWatch.TV** - The Greatest Database of Queer Female, Non-Binary, and Transgender TV"
  introMessage: "Keep up to date with our site status here and don't forget to check out the [**main site**](https://lezwatchtv.com) for more information on Queer TV."
  navbar:
    - title: Status
      href: https://status.lezwatchtv.com
    - title: LWTV
      href: https://lezwatchtv.com
    - title: Docs.
      href: https://docs.lezwatchtv.com
  themeUrl: https://status.lezwatchtv.com/style.css?version=1.0.0
  customHeadHtml: "<script async defer src='https://uptime.ipstenu.com/tracker.js' data-website-id='cmh8h74050cg7387jvs6rdphf'></script>"
