blank_issues_enabled: true
contact_links:
  - name: Feature requests and ideas
    url: https://github.com/orgs/upptime/discussions/new?category=ideas
    about: Suggest an idea for Upptime
  - name: Questions
    url: https://github.com/orgs/upptime/discussions/new?category=q-a
    about: sk and answer questions about Upptime here
